### ISSUE TITLE
Uncaught TypeError: Vue is not a constructor

### ISSUE THREAD

**Issue by michelschilder** [marksitko/vue-sanctum#4]
Does this work with the vue3?

The error is about this line, where it says new Vue() I guess?

var _eventBus = eventBus !== null && eventBus !== void 0 ? eventBus : new Vue(); // if eventBus is not passed, attach a own one to the window object

**Comment by marksitko** [comment]
No, vue-sanctum does not support Vue3 at the moment. I think it should be explicitly rewritten for Vue3 because the Plugin API has changed. But maybe in 2022 :) 
Sorry!
